// ── State-level enrollment data (all 50 states) ─────────────
export const STATE_DATA = {
  AL:{ name:"Alabama",          active_trials:12, enrollment_rate:58, dropout_rate:24, site_activation:71, status:"moderate"  },
  AK:{ name:"Alaska",           active_trials:3,  enrollment_rate:42, dropout_rate:33, site_activation:50, status:"at-risk"   },
  AZ:{ name:"Arizona",          active_trials:28, enrollment_rate:79, dropout_rate:13, site_activation:88, status:"healthy"   },
  AR:{ name:"Arkansas",         active_trials:8,  enrollment_rate:49, dropout_rate:30, site_activation:60, status:"at-risk"   },
  CA:{ name:"California",       active_trials:87, enrollment_rate:83, dropout_rate:11, site_activation:93, status:"healthy"   },
  CO:{ name:"Colorado",         active_trials:31, enrollment_rate:76, dropout_rate:15, site_activation:85, status:"healthy"   },
  CT:{ name:"Connecticut",      active_trials:19, enrollment_rate:68, dropout_rate:19, site_activation:77, status:"moderate"  },
  DE:{ name:"Delaware",         active_trials:6,  enrollment_rate:62, dropout_rate:22, site_activation:72, status:"moderate"  },
  FL:{ name:"Florida",          active_trials:64, enrollment_rate:71, dropout_rate:18, site_activation:84, status:"moderate"  },
  GA:{ name:"Georgia",          active_trials:39, enrollment_rate:64, dropout_rate:21, site_activation:76, status:"moderate"  },
  HI:{ name:"Hawaii",           active_trials:7,  enrollment_rate:77, dropout_rate:13, site_activation:86, status:"healthy"   },
  ID:{ name:"Idaho",            active_trials:9,  enrollment_rate:51, dropout_rate:29, site_activation:61, status:"at-risk"   },
  IL:{ name:"Illinois",         active_trials:52, enrollment_rate:74, dropout_rate:17, site_activation:83, status:"moderate"  },
  IN:{ name:"Indiana",          active_trials:22, enrollment_rate:60, dropout_rate:23, site_activation:72, status:"moderate"  },
  IA:{ name:"Iowa",             active_trials:14, enrollment_rate:78, dropout_rate:14, site_activation:87, status:"healthy"   },
  KS:{ name:"Kansas",           active_trials:11, enrollment_rate:53, dropout_rate:27, site_activation:64, status:"at-risk"   },
  KY:{ name:"Kentucky",         active_trials:17, enrollment_rate:46, dropout_rate:33, site_activation:57, status:"at-risk"   },
  LA:{ name:"Louisiana",        active_trials:21, enrollment_rate:50, dropout_rate:30, site_activation:61, status:"at-risk"   },
  ME:{ name:"Maine",            active_trials:8,  enrollment_rate:72, dropout_rate:17, site_activation:81, status:"moderate"  },
  MD:{ name:"Maryland",         active_trials:33, enrollment_rate:81, dropout_rate:11, site_activation:91, status:"healthy"   },
  MA:{ name:"Massachusetts",    active_trials:47, enrollment_rate:86, dropout_rate:9,  site_activation:94, status:"healthy"   },
  MI:{ name:"Michigan",         active_trials:41, enrollment_rate:69, dropout_rate:20, site_activation:79, status:"moderate"  },
  MN:{ name:"Minnesota",        active_trials:35, enrollment_rate:82, dropout_rate:12, site_activation:92, status:"healthy"   },
  MS:{ name:"Mississippi",      active_trials:10, enrollment_rate:41, dropout_rate:37, site_activation:51, status:"at-risk"   },
  MO:{ name:"Missouri",         active_trials:26, enrollment_rate:63, dropout_rate:22, site_activation:74, status:"moderate"  },
  MT:{ name:"Montana",          active_trials:5,  enrollment_rate:54, dropout_rate:27, site_activation:63, status:"at-risk"   },
  NE:{ name:"Nebraska",         active_trials:12, enrollment_rate:74, dropout_rate:16, site_activation:83, status:"moderate"  },
  NV:{ name:"Nevada",           active_trials:16, enrollment_rate:58, dropout_rate:25, site_activation:68, status:"moderate"  },
  NH:{ name:"New Hampshire",    active_trials:9,  enrollment_rate:71, dropout_rate:17, site_activation:80, status:"moderate"  },
  NJ:{ name:"New Jersey",       active_trials:38, enrollment_rate:79, dropout_rate:14, site_activation:89, status:"healthy"   },
  NM:{ name:"New Mexico",       active_trials:11, enrollment_rate:45, dropout_rate:34, site_activation:55, status:"at-risk"   },
  NY:{ name:"New York",         active_trials:79, enrollment_rate:76, dropout_rate:16, site_activation:86, status:"healthy"   },
  NC:{ name:"North Carolina",   active_trials:44, enrollment_rate:70, dropout_rate:19, site_activation:80, status:"moderate"  },
  ND:{ name:"North Dakota",     active_trials:4,  enrollment_rate:61, dropout_rate:22, site_activation:72, status:"moderate"  },
  OH:{ name:"Ohio",             active_trials:48, enrollment_rate:73, dropout_rate:17, site_activation:82, status:"moderate"  },
  OK:{ name:"Oklahoma",         active_trials:14, enrollment_rate:48, dropout_rate:31, site_activation:59, status:"at-risk"   },
  OR:{ name:"Oregon",           active_trials:24, enrollment_rate:77, dropout_rate:14, site_activation:87, status:"healthy"   },
  PA:{ name:"Pennsylvania",     active_trials:56, enrollment_rate:74, dropout_rate:17, site_activation:84, status:"moderate"  },
  RI:{ name:"Rhode Island",     active_trials:7,  enrollment_rate:67, dropout_rate:21, site_activation:76, status:"moderate"  },
  SC:{ name:"South Carolina",   active_trials:19, enrollment_rate:59, dropout_rate:25, site_activation:70, status:"moderate"  },
  SD:{ name:"South Dakota",     active_trials:5,  enrollment_rate:53, dropout_rate:27, site_activation:62, status:"at-risk"   },
  TN:{ name:"Tennessee",        active_trials:28, enrollment_rate:63, dropout_rate:23, site_activation:74, status:"moderate"  },
  TX:{ name:"Texas",            active_trials:72, enrollment_rate:67, dropout_rate:20, site_activation:79, status:"moderate"  },
  UT:{ name:"Utah",             active_trials:18, enrollment_rate:76, dropout_rate:14, site_activation:85, status:"healthy"   },
  VT:{ name:"Vermont",          active_trials:5,  enrollment_rate:73, dropout_rate:16, site_activation:82, status:"moderate"  },
  VA:{ name:"Virginia",         active_trials:36, enrollment_rate:80, dropout_rate:12, site_activation:90, status:"healthy"   },
  WA:{ name:"Washington",       active_trials:42, enrollment_rate:84, dropout_rate:10, site_activation:94, status:"healthy"   },
  WV:{ name:"West Virginia",    active_trials:8,  enrollment_rate:40, dropout_rate:38, site_activation:49, status:"at-risk"   },
  WI:{ name:"Wisconsin",        active_trials:29, enrollment_rate:76, dropout_rate:15, site_activation:86, status:"healthy"   },
  WY:{ name:"Wyoming",          active_trials:3,  enrollment_rate:47, dropout_rate:32, site_activation:56, status:"at-risk"   },
}

// Derived portfolio KPIs
const allStates     = Object.values(STATE_DATA)
const totalTrials   = allStates.reduce((s, st) => s + st.active_trials, 0)
const healthyCount  = allStates.filter(s => s.status === 'healthy').length
const moderateCount = allStates.filter(s => s.status === 'moderate').length
const atRiskCount   = allStates.filter(s => s.status === 'at-risk').length
const avgEnroll     = Math.round(allStates.reduce((s, st) => s + st.enrollment_rate, 0) / allStates.length)
const avgDropout    = Math.round(allStates.reduce((s, st) => s + st.dropout_rate, 0) / allStates.length)
const avgSiteAct    = Math.round(allStates.reduce((s, st) => s + st.site_activation, 0) / allStates.length)

export const PORTFOLIO_KPIS = {
  total_trials:        totalTrials,
  enrollment_rate:     avgEnroll,
  site_activation:     avgSiteAct,
  dropout_rate:        avgDropout,
  healthy_pct:         Math.round(healthyCount  / 50 * 100),
  moderate_pct:        Math.round(moderateCount / 50 * 100),
  at_risk_pct:         Math.round(atRiskCount   / 50 * 100),
  trials_by_phase: [
    { phase: "Phase I",   count: 124, trend: 2,  up: true  },
    { phase: "Phase II",  count: 89,  trend: 2,  up: false },
    { phase: "Phase III", count: 612, trend: 1,  up: false, alert: true },
    { phase: "Phase IV",  count: 307, trend: 2,  up: true  },
  ],
}

// ── Trial list ───────────────────────────────────────────────
export const TRIALS = [
  {
    id: 1,
    code:             "PREDICT-RD",
    name:             "ctDNA Surveillance in TNBC With Residual Disease",
    phase:            "I",
    status:           "healthy",
    cost_per_patient: 19562,
    enrollment_rate:  90,
    retention_rate:   95,
    dropout_rate:     5,
    screen_failure:   8,
    site_activation:  97,
    last_updated:     "11/02/2025",
    sponsor:          "Oncology Research Corp",
    responsible_party:"Dr. Sarah Mitchell",
    site_health_score: 91,
    ae_reports: 4, severe_ae: 0,
    patient_satisfaction: 92,
    enrollment_pacing: "Ahead of plan by 12 participants",
    dropout_reasons: ["Voluntary withdrawal 60%", "Adverse events 40%"],
    site_activation_time: 18,
    budget_adherence: 2,
    cost_change: -200,
    health_factors: [
      { factor:"Enrollment Rate",    weight:25, score:94 },
      { factor:"Screen Failure Rate",weight:20, score:88 },
      { factor:"Data Entry Lag",     weight:15, score:91 },
      { factor:"Missing Data %",     weight:15, score:87 },
      { factor:"Protocol Deviation", weight:15, score:93 },
      { factor:"Dropout Rate",       weight:10, score:96 },
    ],
    monthly_enrollment: [
      {month:"Jan",enrollment:88,dropout:4},{month:"Apr",enrollment:90,dropout:5},
      {month:"Jul",enrollment:91,dropout:4},{month:"Oct",enrollment:93,dropout:5},{month:"Dec",enrollment:90,dropout:5},
    ],
    monthly_budget: [
      {month:"Jan",budget:100,adherence:102},{month:"Apr",budget:100,adherence:101},
      {month:"Jul",budget:100,adherence:99},{month:"Oct",budget:100,adherence:102},{month:"Dec",budget:100,adherence:100},
    ],
  },
  {
    id: 2,
    code:             "FMISO-BR",
    name:             "Feasibility of FMISO in Brain Tumors",
    phase:            "II",
    status:           "moderate",
    cost_per_patient: 152950,
    enrollment_rate:  69,
    retention_rate:   84,
    dropout_rate:     16,
    screen_failure:   22,
    site_activation:  78,
    last_updated:     "10/19/2025",
    sponsor:          "NeuroClinical Ltd",
    responsible_party:"Dr. James Okafor",
    site_health_score: 71,
    ae_reports: 14, severe_ae: 1,
    patient_satisfaction: 76,
    enrollment_pacing: "Behind plan by 24 participants",
    dropout_reasons: ["Adverse events 55%", "Patient decision 45%"],
    site_activation_time: 28,
    budget_adherence: -4,
    cost_change: 450,
    health_factors: [
      { factor:"Enrollment Rate",    weight:25, score:68 },
      { factor:"Screen Failure Rate",weight:20, score:74 },
      { factor:"Data Entry Lag",     weight:15, score:79 },
      { factor:"Missing Data %",     weight:15, score:72 },
      { factor:"Protocol Deviation", weight:15, score:70 },
      { factor:"Dropout Rate",       weight:10, score:65 },
    ],
    monthly_enrollment: [
      {month:"Jan",enrollment:65,dropout:14},{month:"Apr",enrollment:67,dropout:16},
      {month:"Jul",enrollment:70,dropout:15},{month:"Oct",enrollment:68,dropout:17},{month:"Dec",enrollment:69,dropout:16},
    ],
    monthly_budget: [
      {month:"Jan",budget:100,adherence:97},{month:"Apr",budget:100,adherence:96},
      {month:"Jul",budget:100,adherence:95},{month:"Oct",budget:100,adherence:96},{month:"Dec",budget:100,adherence:96},
    ],
  },
  {
    id: 3,
    code:             "NBM-BMX",
    name:             "For Patients with Solid Tumors or Newly Diagnosed Glioblastoma",
    phase:            "III",
    status:           "at-risk",
    cost_per_patient: 15860,
    enrollment_rate:  60,
    retention_rate:   65,
    dropout_rate:     35,
    screen_failure:   50,
    site_activation:  50,
    last_updated:     "09/03/2025",
    sponsor:          "BioStem Partners",
    responsible_party:"Dr. Anika Patel",
    site_health_score: 56,
    ae_reports: 22, severe_ae: 3,
    patient_satisfaction: 68,
    enrollment_pacing: "Behind plan by 58 participants",
    dropout_reasons: ["Adverse events 43%", "Loss to follow up 21%", "Physician decision 36%"],
    site_activation_time: 22,
    budget_adherence: -8,
    cost_change: 800,
    health_factors: [
      { factor:"Enrollment Rate",    weight:25, score:48 },
      { factor:"Screen Failure Rate",weight:20, score:62 },
      { factor:"Data Entry Lag",     weight:15, score:71 },
      { factor:"Missing Data %",     weight:15, score:67 },
      { factor:"Protocol Deviation", weight:15, score:54 },
      { factor:"Dropout Rate",       weight:10, score:42 },
    ],
    monthly_enrollment: [
      {month:"Jan",enrollment:64,dropout:32},{month:"Apr",enrollment:62,dropout:34},
      {month:"Jul",enrollment:60,dropout:36},{month:"Oct",enrollment:59,dropout:37},{month:"Dec",enrollment:60,dropout:35},
    ],
    monthly_budget: [
      {month:"Jan",budget:100,adherence:94},{month:"Apr",budget:100,adherence:93},
      {month:"Jul",budget:100,adherence:92},{month:"Oct",budget:100,adherence:91},{month:"Dec",budget:100,adherence:92},
    ],
  },
  {
    id: 4,
    code:             "FLUO-BR",
    name:             "Fluorescence Guided Resection in Breast Cancer",
    phase:            "IV",
    status:           "healthy",
    cost_per_patient: 68300,
    enrollment_rate:  95,
    retention_rate:   90,
    dropout_rate:     10,
    screen_failure:   6,
    site_activation:  96,
    last_updated:     "10/16/2025",
    sponsor:          "SurgTech Medical",
    responsible_party:"Dr. Lisa Chen",
    site_health_score: 93,
    ae_reports: 3, severe_ae: 0,
    patient_satisfaction: 94,
    enrollment_pacing: "Ahead of plan by 20 participants",
    dropout_reasons: ["Voluntary withdrawal 70%", "Relocation 30%"],
    site_activation_time: 14,
    budget_adherence: 3,
    cost_change: -300,
    health_factors: [
      { factor:"Enrollment Rate",    weight:25, score:97 },
      { factor:"Screen Failure Rate",weight:20, score:91 },
      { factor:"Data Entry Lag",     weight:15, score:94 },
      { factor:"Missing Data %",     weight:15, score:89 },
      { factor:"Protocol Deviation", weight:15, score:95 },
      { factor:"Dropout Rate",       weight:10, score:90 },
    ],
    monthly_enrollment: [
      {month:"Jan",enrollment:93,dropout:9},{month:"Apr",enrollment:95,dropout:10},
      {month:"Jul",enrollment:96,dropout:9},{month:"Oct",enrollment:95,dropout:10},{month:"Dec",enrollment:95,dropout:10},
    ],
    monthly_budget: [
      {month:"Jan",budget:100,adherence:103},{month:"Apr",budget:100,adherence:102},
      {month:"Jul",budget:100,adherence:104},{month:"Oct",budget:100,adherence:103},{month:"Dec",budget:100,adherence:103},
    ],
  },
  {
    id: 5,
    code:             "GBM-RT",
    name:             "Glioblastoma Radiotherapy Using IMRT or Proton Beams",
    phase:            "IV",
    status:           "moderate",
    cost_per_patient: 203950,
    enrollment_rate:  73,
    retention_rate:   86,
    dropout_rate:     14,
    screen_failure:   18,
    site_activation:  82,
    last_updated:     "10/23/2025",
    sponsor:          "RadOnc Institute",
    responsible_party:"Dr. Robert Zhang",
    site_health_score: 74,
    ae_reports: 11, severe_ae: 1,
    patient_satisfaction: 79,
    enrollment_pacing: "Behind plan by 18 participants",
    dropout_reasons: ["Adverse events 48%", "Patient decision 52%"],
    site_activation_time: 25,
    budget_adherence: -3,
    cost_change: 600,
    health_factors: [
      { factor:"Enrollment Rate",    weight:25, score:72 },
      { factor:"Screen Failure Rate",weight:20, score:76 },
      { factor:"Data Entry Lag",     weight:15, score:81 },
      { factor:"Missing Data %",     weight:15, score:74 },
      { factor:"Protocol Deviation", weight:15, score:73 },
      { factor:"Dropout Rate",       weight:10, score:68 },
    ],
    monthly_enrollment: [
      {month:"Jan",enrollment:71,dropout:13},{month:"Apr",enrollment:72,dropout:14},
      {month:"Jul",enrollment:74,dropout:13},{month:"Oct",enrollment:73,dropout:15},{month:"Dec",enrollment:73,dropout:14},
    ],
    monthly_budget: [
      {month:"Jan",budget:100,adherence:98},{month:"Apr",budget:100,adherence:97},
      {month:"Jul",budget:100,adherence:97},{month:"Oct",budget:100,adherence:97},{month:"Dec",budget:100,adherence:97},
    ],
  },
  {
    id: 6,
    code:             "LUNG-IMM",
    name:             "Immunotherapy Combined With Chemotherapy in NSCLC",
    phase:            "III",
    status:           "at-risk",
    cost_per_patient: 42100,
    enrollment_rate:  52,
    retention_rate:   71,
    dropout_rate:     29,
    screen_failure:   38,
    site_activation:  61,
    last_updated:     "09/28/2025",
    sponsor:          "PharmaGen Corp",
    responsible_party:"Dr. Michael Torres",
    site_health_score: 49,
    ae_reports: 31, severe_ae: 5,
    patient_satisfaction: 61,
    enrollment_pacing: "Behind plan by 74 participants",
    dropout_reasons: ["Adverse events 52%", "Loss to follow up 29%", "Physician decision 19%"],
    site_activation_time: 34,
    budget_adherence: -12,
    cost_change: 1200,
    health_factors: [
      { factor:"Enrollment Rate",    weight:25, score:41 },
      { factor:"Screen Failure Rate",weight:20, score:55 },
      { factor:"Data Entry Lag",     weight:15, score:63 },
      { factor:"Missing Data %",     weight:15, score:58 },
      { factor:"Protocol Deviation", weight:15, score:47 },
      { factor:"Dropout Rate",       weight:10, score:38 },
    ],
    monthly_enrollment: [
      {month:"Jan",enrollment:58,dropout:26},{month:"Apr",enrollment:55,dropout:28},
      {month:"Jul",enrollment:53,dropout:30},{month:"Oct",enrollment:51,dropout:31},{month:"Dec",enrollment:52,dropout:29},
    ],
    monthly_budget: [
      {month:"Jan",budget:100,adherence:91},{month:"Apr",budget:100,adherence:89},
      {month:"Jul",budget:100,adherence:88},{month:"Oct",budget:100,adherence:87},{month:"Dec",budget:100,adherence:88},
    ],
  },
]

// ── Commercial Insights Portal ────────────────────────────────

export const COMMERCIAL_STATE_SCORES = {
  AL:58, AK:45, AZ:72, AR:51, CA:91, CO:76, CT:81, DE:69, FL:83, GA:74,
  HI:55, ID:48, IL:85, IN:67, IA:59, KS:54, KY:61, LA:63, ME:57, MD:79,
  MA:88, MI:73, MN:77, MS:49, MO:68, MT:44, NE:56, NV:70, NH:73, NJ:84,
  NM:52, NY:91, NC:78, ND:42, OH:76, OK:55, OR:71, PA:82, RI:75, SC:65,
  SD:47, TN:69, TX:87, UT:66, VT:62, VA:80, WA:83, WV:46, WI:71, WY:43, DC:90,
}

export const STATE_TO_REGION = {
  ME:'New England', NH:'New England', VT:'New England', MA:'New England', RI:'New England', CT:'New England',
  NY:'Mid-Atlantic', NJ:'Mid-Atlantic', PA:'Mid-Atlantic', DE:'Mid-Atlantic', MD:'Mid-Atlantic', DC:'Mid-Atlantic',
  VA:'Southeast', WV:'Southeast', NC:'Southeast', SC:'Southeast', GA:'Southeast', FL:'Southeast',
  AL:'Southeast', MS:'Southeast', TN:'Southeast', KY:'Southeast',
  OH:'Midwest', IN:'Midwest', MI:'Midwest', IL:'Midwest', WI:'Midwest', MN:'Midwest',
  IA:'Midwest', MO:'Midwest', ND:'Midwest', SD:'Midwest', NE:'Midwest', KS:'Midwest',
  TX:'Southwest', OK:'Southwest', AR:'Southwest', LA:'Southwest', NM:'Southwest', AZ:'Southwest',
  CO:'Mountain', WY:'Mountain', MT:'Mountain', ID:'Mountain', UT:'Mountain', NV:'Mountain',
  CA:'Pacific', OR:'Pacific', WA:'Pacific', AK:'Pacific', HI:'Pacific',
}

export const COMMERCIAL_REGIONS = {
  'Mid-Atlantic': {
    score: 224, trend: -2,
    field:      { prescriber_loyalty: 84, coverage: 92, access_barriers: 8,  competing_influence: 28 },
    marketing:  { diagnostic_alignment: '2x', email: 29, cme: 31, in_person: 21 },
    pre_launch: { roi: '2x', email: 23, cme: 26, in_person: 23 },
  },
  'Southeast': {
    score: 238, trend: 3,
    field:      { prescriber_loyalty: 79, coverage: 87, access_barriers: 14, competing_influence: 42 },
    marketing:  { diagnostic_alignment: '1.8x', email: 32, cme: 28, in_person: 24 },
    pre_launch: { roi: '1.7x', email: 25, cme: 22, in_person: 27 },
  },
  'Midwest': {
    score: 219, trend: 1,
    field:      { prescriber_loyalty: 76, coverage: 85, access_barriers: 16, competing_influence: 38 },
    marketing:  { diagnostic_alignment: '1.6x', email: 27, cme: 33, in_person: 19 },
    pre_launch: { roi: '1.5x', email: 22, cme: 28, in_person: 21 },
  },
  'Southwest': {
    score: 231, trend: 4,
    field:      { prescriber_loyalty: 81, coverage: 89, access_barriers: 11, competing_influence: 35 },
    marketing:  { diagnostic_alignment: '2.1x', email: 31, cme: 29, in_person: 26 },
    pre_launch: { roi: '2.2x', email: 27, cme: 24, in_person: 25 },
  },
  'Mountain': {
    score: 198, trend: -1,
    field:      { prescriber_loyalty: 68, coverage: 76, access_barriers: 21, competing_influence: 44 },
    marketing:  { diagnostic_alignment: '1.3x', email: 24, cme: 26, in_person: 17 },
    pre_launch: { roi: '1.2x', email: 20, cme: 21, in_person: 18 },
  },
  'Pacific': {
    score: 247, trend: 5,
    field:      { prescriber_loyalty: 88, coverage: 94, access_barriers: 6,  competing_influence: 29 },
    marketing:  { diagnostic_alignment: '2.4x', email: 34, cme: 30, in_person: 28 },
    pre_launch: { roi: '2.5x', email: 29, cme: 27, in_person: 29 },
  },
  'New England': {
    score: 233, trend: 2,
    field:      { prescriber_loyalty: 83, coverage: 91, access_barriers: 9,  competing_influence: 31 },
    marketing:  { diagnostic_alignment: '2x', email: 30, cme: 32, in_person: 22 },
    pre_launch: { roi: '1.9x', email: 24, cme: 25, in_person: 24 },
  },
}

export const COMMERCIAL_KPIS = {
  total_score: 241,
  score_trend: 3,
  strong_pct: 54,
  moderate_pct: 31,
  at_risk_pct: 15,
  coverage_efficiency: 94,
  coverage_trend: 2,
  prescription_lift: 81,
  prescription_trend: 2,
  switch_prevention: 21,
  switch_trend: -1,
  diagnostic_alignment: 50,
  diagnostic_trend: 3,
  hcp_coverage: 92,
  hcp_trend: 5,
  prescriber_loyalty: 84,
  loyalty_trend: 3,
  access_barriers: 12,
  access_level: 'Low',
  competing_brand_influence: 39,
  competing_level: 'Medium',
  field_feedback_issues: 29,
  brand_perception_index: 71,
}

export const COMMERCIAL_MONTHLY = [
  { month:'Jan', contacts:420, scripts:380, feedback:3,  perception:68 },
  { month:'Feb', contacts:445, scripts:395, feedback:4,  perception:69 },
  { month:'Mar', contacts:462, scripts:410, feedback:3,  perception:70 },
  { month:'Apr', contacts:478, scripts:428, feedback:5,  perception:69 },
  { month:'May', contacts:491, scripts:444, feedback:4,  perception:71 },
  { month:'Jun', contacts:510, scripts:460, feedback:6,  perception:70 },
  { month:'Jul', contacts:528, scripts:477, feedback:4,  perception:72 },
  { month:'Aug', contacts:514, scripts:465, feedback:5,  perception:71 },
  { month:'Sep', contacts:535, scripts:488, feedback:7,  perception:73 },
  { month:'Oct', contacts:549, scripts:502, feedback:5,  perception:72 },
  { month:'Nov', contacts:561, scripts:518, feedback:6,  perception:74 },
  { month:'Dec', contacts:574, scripts:531, feedback:4,  perception:75 },
]

export const COMMERCIAL_TOPICS = [
  { topic:'Clinical Trial Questions', positive:45, neutral:35, negative:20, total:120 },
  { topic:'Real World Evidence',      positive:38, neutral:42, negative:20, total:100 },
  { topic:'Factorial Trials',         positive:32, neutral:40, negative:28, total:80  },
  { topic:'Ophthalmology',            positive:28, neutral:45, negative:27, total:70  },
  { topic:'Competitor Drugs',         positive:15, neutral:30, negative:55, total:60  },
  { topic:'Dosing & Safety',          positive:41, neutral:38, negative:21, total:55  },
]

export const COMMERCIAL_SENTIMENT = [
  { month:'Jan', pos:65, neu:25, neg:10 },
  { month:'Feb', pos:67, neu:24, neg:9  },
  { month:'Mar', pos:64, neu:27, neg:9  },
  { month:'Apr', pos:68, neu:23, neg:9  },
  { month:'May', pos:70, neu:22, neg:8  },
  { month:'Jun', pos:69, neu:23, neg:8  },
  { month:'Jul', pos:72, neu:21, neg:7  },
  { month:'Aug', pos:71, neu:22, neg:7  },
  { month:'Sep', pos:73, neu:20, neg:7  },
  { month:'Oct', pos:75, neu:19, neg:6  },
  { month:'Nov', pos:74, neu:20, neg:6  },
  { month:'Dec', pos:76, neu:18, neg:6  },
]
